program FR01;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  FrmMain in 'App\FrmMain.pas' {FormFR62},
  FrmMainRes in 'App\FrmMainRes.pas',
  RiggVar.App.Config in 'App\RiggVar.App.Config.pas',
  RiggVar.App.GuiInterface in 'App\RiggVar.App.GuiInterface.pas',
  RiggVar.App.GuiManager in 'App\RiggVar.App.GuiManager.pas',
  RiggVar.App.Injections in 'App\RiggVar.App.Injections.pas',
  RiggVar.App.Injector in 'App\RiggVar.App.Injector.pas',
  RiggVar.App.Main in 'App\RiggVar.App.Main.pas',
  RiggVar.App.Translation in 'App\RiggVar.App.Translation.pas',
  RiggVar.BO.AngularPost in 'BO\RiggVar.BO.AngularPost.pas',
  RiggVar.BO.Base in 'BO\RiggVar.BO.Base.pas',
  RiggVar.BO.CacheMotor in 'BO\RiggVar.BO.CacheMotor.pas',
  RiggVar.BO.Container in 'BO\RiggVar.BO.Container.pas',
  RiggVar.BO.Def in 'BO\RiggVar.BO.Def.pas',
  RiggVar.BO.EventProps in 'BO\RiggVar.BO.EventProps.pas',
  RiggVar.BO.ExcelExport in 'BO\RiggVar.BO.ExcelExport.pas',
  RiggVar.BO.ExcelImport in 'BO\RiggVar.BO.ExcelImport.pas',
  RiggVar.BO.FolderInfo in 'BO\RiggVar.BO.FolderInfo.pas',
  RiggVar.BO.FormAdapter in 'BO\RiggVar.BO.FormAdapter.pas',
  RiggVar.BO.IniImage in 'BO\RiggVar.BO.IniImage.pas',
  RiggVar.BO.Localizer in 'BO\RiggVar.BO.Localizer.pas',
  RiggVar.BO.Manager in 'BO\RiggVar.BO.Manager.pas',
  RiggVar.BO.Msg in 'BO\RiggVar.BO.Msg.pas',
  RiggVar.BO.MsgBase in 'BO\RiggVar.BO.MsgBase.pas',
  RiggVar.BO.MsgParser in 'BO\RiggVar.BO.MsgParser.pas',
  RiggVar.BO.MsgToken in 'BO\RiggVar.BO.MsgToken.pas',
  RiggVar.BO.MsgTree in 'BO\RiggVar.BO.MsgTree.pas',
  RiggVar.BO.Params in 'BO\RiggVar.BO.Params.pas',
  RiggVar.BO.Penalty in 'BO\RiggVar.BO.Penalty.pas',
  RiggVar.BO.PenaltyISAF in 'BO\RiggVar.BO.PenaltyISAF.pas',
  RiggVar.BO.ResourceManager in 'BO\RiggVar.BO.ResourceManager.pas',
  RiggVar.BO.ResultHash in 'BO\RiggVar.BO.ResultHash.pas',
  RiggVar.BO.SDI in 'BO\RiggVar.BO.SDI.pas',
  RiggVar.BO.StartInfo in 'BO\RiggVar.BO.StartInfo.pas',
  RiggVar.BO.StoreAdapter in 'BO\RiggVar.BO.StoreAdapter.pas',
  RiggVar.BO.TemplateIDs in 'BO\RiggVar.BO.TemplateIDs.pas',
  RiggVar.BO.Time in 'BO\RiggVar.BO.Time.pas',
  RiggVar.BO.UndoManager in 'BO\RiggVar.BO.UndoManager.pas',
  RiggVar.BO.UniquaPoints in 'BO\RiggVar.BO.UniquaPoints.pas',
  RiggVar.BO.Validation in 'BO\RiggVar.BO.Validation.pas',
  RiggVar.BO.Watches in 'BO\RiggVar.BO.Watches.pas',
  RiggVar.BO.Writer in 'BO\RiggVar.BO.Writer.pas',
  RiggVar.BO.WriterJson in 'BO\RiggVar.BO.WriterJson.pas',
  RiggVar.Calc.EV in 'Calc\RiggVar.Calc.EV.pas',
  RiggVar.Calc.EventProxy00 in 'Calc\RiggVar.Calc.EventProxy00.pas',
  RiggVar.Calc.EventProxy01 in 'Calc\RiggVar.Calc.EventProxy01.pas',
  RiggVar.Calc.EventProxy06 in 'Calc\RiggVar.Calc.EventProxy06.pas',
  RiggVar.Col.BaseEntry in 'Col\RiggVar.Col.BaseEntry.pas',
  RiggVar.Col.Captions in 'Col\RiggVar.Col.Captions.pas',
  RiggVar.Col.CategoryCache in 'Col\RiggVar.Col.CategoryCache.pas',
  RiggVar.Col.Event in 'Col\RiggVar.Col.Event.pas',
  RiggVar.Col.NameField in 'Col\RiggVar.Col.NameField.pas',
  RiggVar.Col.NameValue in 'Col\RiggVar.Col.NameValue.pas',
  RiggVar.Col.Race in 'Col\RiggVar.Col.Race.pas',
  RiggVar.Col.Stammdaten in 'Col\RiggVar.Col.Stammdaten.pas',
  RiggVar.Col.Uniqua in 'Col\RiggVar.Col.Uniqua.pas',
  RiggVar.Conn.Def in 'Conn\RiggVar.Conn.Def.pas',
  RiggVar.Conn.Intern in 'Conn\RiggVar.Conn.Intern.pas',
  RiggVar.Conn.IO in 'Conn\RiggVar.Conn.IO.pas',
  RiggVar.DAL.AdapterBase in 'DAL\RiggVar.DAL.AdapterBase.pas',
  RiggVar.DAL.AdapterImpl in 'DAL\RiggVar.DAL.AdapterImpl.pas',
  RiggVar.DAL.Intf in 'DAL\RiggVar.DAL.Intf.pas',
  RiggVar.DAL.Manager in 'DAL\RiggVar.DAL.Manager.pas',
  RiggVar.DAL.Redirector in 'DAL\RiggVar.DAL.Redirector.pas',
  RiggVar.DAL.WorkspaceInfo in 'DAL\RiggVar.DAL.WorkspaceInfo.pas',
  RiggVar.DAL.WorkspaceIntf in 'DAL\RiggVar.DAL.WorkspaceIntf.pas',
  RiggVar.EM.CategoryCache in 'EM\RiggVar.EM.CategoryCache.pas',
  RiggVar.EM.Collection in 'EM\RiggVar.EM.Collection.pas',
  RiggVar.EM.Combo in 'EM\RiggVar.EM.Combo.pas',
  RiggVar.EM.ConApp in 'EM\RiggVar.EM.ConApp.pas',
  RiggVar.EM.ConFile in 'EM\RiggVar.EM.ConFile.pas',
  RiggVar.EM.ConHttp in 'EM\RiggVar.EM.ConHttp.pas',
  RiggVar.EM.ConHttp01 in 'EM\RiggVar.EM.ConHttp01.pas',
  RiggVar.EM.Connection in 'EM\RiggVar.EM.Connection.pas',
  RiggVar.EM.EventData in 'EM\RiggVar.EM.EventData.pas',
  RiggVar.EM.Impl in 'EM\RiggVar.EM.Impl.pas',
  RiggVar.EM.Intf in 'EM\RiggVar.EM.Intf.pas',
  RiggVar.EM.Mock in 'EM\RiggVar.EM.Mock.pas',
  RiggVar.EM.Parser in 'EM\RiggVar.EM.Parser.pas',
  RiggVar.EM.ParserXslt in 'EM\RiggVar.EM.ParserXslt.pas',
  RiggVar.EM.ParserSimple in 'EM\RiggVar.EM.ParserSimple.pas',
  RiggVar.EM.SpeedBtn in 'EM\RiggVar.EM.SpeedBtn.pas',
  RiggVar.EM.SpeedBtn01 in 'EM\RiggVar.EM.SpeedBtn01.pas',
  RiggVar.EM.SpeedBtn02 in 'EM\RiggVar.EM.SpeedBtn02.pas',
  RiggVar.EM.SpeedBtn03 in 'EM\RiggVar.EM.SpeedBtn03.pas',
  RiggVar.EM.SpeedBtnMgr in 'EM\RiggVar.EM.SpeedBtnMgr.pas',
  RiggVar.EM.TestData in 'EM\RiggVar.EM.TestData.pas',
  RiggVar.EM.Transformer in 'EM\RiggVar.EM.Transformer.pas',
  RiggVar.EM.TransformerHtml in 'EM\RiggVar.EM.TransformerHtml.pas',
  RiggVar.EM.TransformerMSXML in 'EM\RiggVar.EM.TransformerMSXML.pas',
  RiggVar.EM.TransformerXml in 'EM\RiggVar.EM.TransformerXml.pas',
  RiggVar.EM.XmlVerySimple in 'EM\RiggVar.EM.XmlVerySimple.pas',
  RiggVar.EM.WorkspaceList in 'EM\RiggVar.EM.WorkspaceList.pas',
  RiggVar.EM.WorkspaceListBase in 'EM\RiggVar.EM.WorkspaceListBase.pas',
  RiggVar.EM.WorkspaceList01 in 'EM\RiggVar.EM.WorkspaceList01.pas',
  FmEntries in 'Tabs\FmEntries.pas' {EntriesTab: TFrame},
  FmEvent in 'Tabs\FmEvent.pas' {EventTab: TFrame},
  FmMenu in 'Tabs\FmMenu.pas' {MenuTab: TFrame},
  FmRacing in 'Tabs\FmRacing.pas' {RacingTab: TFrame},
  FmKeying in 'Tabs\FmKeying.pas' {KeyTab: TFrame},
  FmReport in 'Tabs\FmReport.pas' {ReportTab: TFrame},
  FmWorkspace in 'Tabs\FmWorkspace.pas' {WorkspaceTab: TFrame},
  FmCategory in 'Tabs\FmCategory.pas' {CategoryTab: TFrame},
  FmMobil in 'Tabs\FmMobil.pas' {MobilTab: TFrame},
  RiggVar.Grid.Block in 'Grid\RiggVar.Grid.Block.pas',
  RiggVar.Grid.BlockHtml in 'Grid\RiggVar.Grid.BlockHtml.pas',
  RiggVar.Grid.ColBase in 'Grid\RiggVar.Grid.ColBase.pas',
  RiggVar.Grid.ColGrid in 'Grid\RiggVar.Grid.ColGrid.pas',
  RiggVar.Grid.Color in 'Grid\RiggVar.Grid.Color.pas',
  RiggVar.Grid.Control in 'Grid\RiggVar.Grid.Control.pas',
  RiggVar.Grid.Model in 'Grid\RiggVar.Grid.Model.pas',
  RiggVar.Grid.SimpleBlock in 'Grid\RiggVar.Grid.SimpleBlock.pas',
  RiggVar.Grid.SimpleControl in 'Grid\RiggVar.Grid.SimpleControl.pas',
  RiggVar.Grid.SimpleModel in 'Grid\RiggVar.Grid.SimpleModel.pas',
  RiggVar.Grid.Update in 'Grid\RiggVar.Grid.Update.pas',
  RiggVar.Mobil.Facade in 'Mobil\RiggVar.Mobil.Facade.pas',
  RiggVar.Mobil.GridBlock in 'Mobil\RiggVar.Mobil.GridBlock.pas',
  RiggVar.Scoring.Base in 'JS01\RiggVar.Scoring.Base.pas',
  RiggVar.Scoring.Bonus in 'JS01\RiggVar.Scoring.Bonus.pas',
  RiggVar.Scoring.BonusDSV in 'JS01\RiggVar.Scoring.BonusDSV.pas',
  RiggVar.Scoring.Classes in 'JS01\RiggVar.Scoring.Classes.pas',
  RiggVar.Scoring.Defs in 'JS01\RiggVar.Scoring.Defs.pas',
  RiggVar.Scoring.Domain in 'JS01\RiggVar.Scoring.Domain.pas',
  RiggVar.Scoring.LowPoint in 'JS01\RiggVar.Scoring.LowPoint.pas',
  RiggVar.Scoring.Penalty in 'JS01\RiggVar.Scoring.Penalty.pas',
  RiggVar.Scoring.Proxy in 'JS01\RiggVar.Scoring.Proxy.pas',
  RiggVar.Scoring.Time in 'JS01\RiggVar.Scoring.Time.pas',
  RiggVar.Scoring.Utils in 'JS01\RiggVar.Scoring.Utils.pas',
  RiggVar.Out.Base in 'Out\RiggVar.Out.Base.pas',
  RiggVar.Out.FR00 in 'Out\RiggVar.Out.FR00.pas',
  RiggVar.Out.FR06 in 'Out\RiggVar.Out.FR06.pas',
  RiggVar.Out.GridBlock in 'Out\RiggVar.Out.GridBlock.pas',
  RiggVar.Out.Intf in 'Out\RiggVar.Out.Intf.pas',
  RiggVar.Out.Json in 'Out\RiggVar.Out.Json.pas',
  RiggVar.Util.AppUtils in 'Util\RiggVar.Util.AppUtils.pas',
  RiggVar.Util.Classes in 'Util\RiggVar.Util.Classes.pas',
  RiggVar.Util.InfoMemo in 'Util\RiggVar.Util.InfoMemo.pas',
  RiggVar.Util.InputMatrix in 'Util\RiggVar.Util.InputMatrix.pas',
  RiggVar.Util.ItemCollection in 'Util\RiggVar.Util.ItemCollection.pas',
  RiggVar.Util.Logger in 'Util\RiggVar.Util.Logger.pas',
  RiggVar.Util.LoggerDebug in 'Util\RiggVar.Util.LoggerDebug.pas',
  RiggVar.Util.Props in 'Util\RiggVar.Util.Props.pas';

{$R *.RES}
{$R Xml_RC.RES}

begin
  Application.Initialize;
  TStyleManager.TrySetStyle('Iceberg Classico');
  Application.Title := 'FR01';
  InjectorImpl := TInjectorImpl.Create;
  Main := TMain.Create;
  Application.CreateForm(TFormFR62, FormFR62);
  Application.MainForm.Caption := 'FR01 - FR';
  Main.Params.NoAutoSave := true;
  Application.Run;
  FormFR62.Free;
  Main.Free;

end.
